FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY prisma ./prisma
RUN npx prisma generate
COPY . .
EXPOSE 8281
CMD ["sh", "-c", "until nc -z db 5432; do echo 'Waiting for database...'; sleep 1; done; npx prisma generate && npx prisma db push && node seed.js && npx nodemon -L src/app.js"]
